import { Router, type IRouter } from "express";
import healthRouter from "./health";
import organizationsRouter from "./organizations";
import usersRouter from "./users";
import rolesRouter from "./roles";
import employeesRouter from "./employees";
import interviewsRouter from "./interviews";
import tasksRouter from "./tasks";
import workflowsRouter from "./workflows";
import conversationsRouter from "./conversations";
import integrationsRouter from "./integrations";
import billingRouter from "./billing";
import notificationsRouter from "./notifications";
import supportRouter from "./support";
import dashboardRouter from "./dashboard";
import voicesRouter from "./voices";
import storageRouter from "./storage";
import avatarsRouter from "./avatars";
import voiceRouter from "./voice";
import personalityRouter from "./personality";
import promptsRouter from "./prompts";
import orchestrationRouter from "./orchestration";
import toolsRouter from "./tools";
import videoStudioRouter from "./video-studio";
import apiKeysRouter from "./api-keys";
import ariaRouter from "./aria";
import videoCallRouter from "./videoCall";
import memoryRouter from "./memory";
import proactiveRulesRouter from "./proactive-rules";
import analyticsRouter from "./analytics";
import complianceRouter from "./compliance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(organizationsRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(employeesRouter);
router.use(interviewsRouter);
router.use(tasksRouter);
router.use(workflowsRouter);
router.use(conversationsRouter);
router.use(integrationsRouter);
router.use(billingRouter);
router.use(notificationsRouter);
router.use(supportRouter);
router.use(dashboardRouter);
router.use(voicesRouter);
router.use(storageRouter);
router.use(avatarsRouter);
router.use(voiceRouter);
router.use(personalityRouter);
router.use(promptsRouter);
router.use(orchestrationRouter);
router.use(toolsRouter);
router.use(videoStudioRouter);
router.use(apiKeysRouter);
router.use(ariaRouter);
router.use(videoCallRouter);
router.use(memoryRouter);
router.use(proactiveRulesRouter);
router.use(analyticsRouter);
router.use(complianceRouter);

export default router;
